name: Deploy API Spec
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: mkdir gh-pages
      - run: cp redoc.html gh-pages/index.html
      - run: cp openapi.yaml gh-pages/openapi.yaml
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          user_name: 'CI'
          user_email: ci@mohr.ws